services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telecontrol_app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
    environment:
      - APP_ENV=local
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: telecontrol_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: telecontrol
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appsecret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  dbdata: {}
